//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YANGILDIN_GLAZKI_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentPriorityHistory
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int PriorityValue { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
