//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YANGILDIN_GLAZKI_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.MaterialCountHistory = new HashSet<MaterialCountHistory>();
            this.ProductMaterial = new HashSet<ProductMaterial>();
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int CountInPack { get; set; }
        public string Unit { get; set; }
        public Nullable<double> CountInStock { get; set; }
        public double MinCount { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public string Image { get; set; }
        public int MaterialTypeID { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual ICollection<MaterialCountHistory> MaterialCountHistory { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}
