//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YANGILDIN_GLAZKI_PROJECT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yangildin_glazkiEntities : DbContext
    {
        private static yangildin_glazkiEntities _context;
        public static yangildin_glazkiEntities GetContext()
        {
            if (_context == null)
                _context = new yangildin_glazkiEntities();
            return _context;
        }
        


        public yangildin_glazkiEntities()
            : base("name=yangildin_glazkiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agent> Agent { get; set; }
        public DbSet<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public DbSet<AgentType> AgentType { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialCountHistory> MaterialCountHistory { get; set; }
        public DbSet<MaterialType> MaterialType { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductCostHistory> ProductCostHistory { get; set; }
        public DbSet<ProductMaterial> ProductMaterial { get; set; }
        public DbSet<ProductSale> ProductSale { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<Shop> Shop { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
    }
}
